### ISSUE TITLE
[QUESTION] styled-component in another styled-component snapshot

### ISSUE THREAD

**Issue by ZouYouShun** [styled-components/jest-styled-components#346]
Hi team, there is an issue from our project, if we styled a styled-component in another styled-component, there will generate that original `sc-` begin class name, how can I resolve that, that will update that class name every time when I add some file.
```tsx
import 'jest-styled-components';

import React from 'react';
import renderer from 'react-test-renderer';
import styled from 'styled-components';

const Button2 = styled.button`
  color: red;
`;

const Button = styled.button`
  color: red;
  ${Button2} {
    color: black;
  }
`;

test('it works', () => {
  const tree = renderer.create(<Button />).toJSON();
  expect(tree).toMatchSnapshot();
  expect(tree).toHaveStyleRule('color', 'red');
});
```

```css
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`it works 1`] = `
.c0 {
  color: red;
}

.c0 .sc-bdnylx {
  color: black;
}

<button
  className="c0"
/>
`;
```
