### ISSUE TITLE
Cannot find module pretty-format or type declarations err with yarn 2

### ISSUE THREAD

**Issue by WCByrne** [styled-components/jest-styled-components#386]
I'm using jest-styled-components in a project that uses yarn 2. It looks like jest-styled-components references pretty-format in typings/index.d.ts but pretty-format is not included as a dependency. I believe this causes issues with yarn 2. 

Adding the following to `yarnrc.yml` resolves the issue but this should really be fixed in the package itself.
```
packageExtensions:
  jest-styled-components@*:
    dependencies:
      pretty-format: "*"
```
